### PR TITLE
Removed dependency on segmatch and segmatch_ros

### PR DESCRIPTION
**Pull request by rdube**
I moved pcl typedefs and functions from segmatch common.hpp to laser_slam.hpp and am getting the following boost error:
```
In file included from /usr/include/boost/mpl/aux_/has_apply.hpp:17:0,
                 from /usr/include/boost/mpl/apply_wrap.hpp:23,
                 from /usr/include/boost/mpl/aux_/numeric_op.hpp:22,
                 from /usr/include/boost/mpl/aux_/comparison_op.hpp:27,
                 from /usr/include/boost/mpl/equal_to.hpp:19,
                 from /usr/include/boost/serialization/tracking.hpp:24,
                 from /usr/include/boost/serialization/nvp.hpp:32,
                 from /home/renaud/catkin_ws/devel/include/gtsam/base/Vector.h:349,
                 from /home/renaud/catkin_ws/devel/include/gtsam/base/Matrix.h:24,
                 from /home/renaud/catkin_ws/devel/include/gtsam/base/Manifold.h:22,
                 from /home/renaud/catkin_ws/devel/include/gtsam/base/Lie.h:25,
                 from /home/renaud/catkin_ws/devel/include/gtsam/base/VectorSpace.h:11,
                 from /home/renaud/catkin_ws/devel/include/gtsam/geometry/Point2.h:20,
                 from /home/renaud/catkin_ws/devel/include/gtsam/nonlinear/NonlinearFactorGraph.h:24,
                 from /home/renaud/catkin_ws/src/laser_slam/laser_slam/include/laser_slam/laser_track.hpp:7,
                 from /home/renaud/catkin_ws/src/laser_slam/laser_slam/src/laser_track.cpp:1:
/usr/include/boost/range/has_range_iterator.hpp: At global scope:
/usr/include/boost/range/has_range_iterator.hpp:22:9: error: expected type-specifier
         BOOST_MPL_HAS_XXX_TRAIT_DEF(type)
```

We are not using boost directly but gtsam does.  @gawela @HannesSommer any idea where that could come from? Thanks!

### CODE REVIEW

**Comment by HannesSommer** [comment]
It seems impossible to me that this is caused by the changes in `common.hpp` , because it seems to be included later (after this error is caused - or is the error message incomplete?). If this is caused by the changes in this PR then it should caused compiler flags and therefore by the changes in the `CMakeLists.txt`.
Btw. : I'd remove this https://github.com/ethz-asl/laser_slam/blob/feature/laser_slam_worker/laser_slam/include/laser_slam/laser_track.hpp#L4 if it is not needed. (slows your compiler down unnecessarily)

**Comment by rdube** [comment]
Thanks @HannesSommer !

**Comment by rdube** [comment]
@HannesSommer I guess the only big change is that the laser_slam package which previously depended on GTSAM also now depends on PCL. I cannot explain how this is causing the issue though.

As a note, laser_slam does not currently depend on PCL but laser_slam_ros, segmatch and segmatch_ros do. I initially moved the functions there but that could actually be moved to laser_slam_ros. However, I did not want segmatch to depend on laser_slam_ros. Would it make sense to create some kind of PCL wrapper which would provide these typedefs and functionalities? laser_slam would then not have to depend on that package and the boost error might go away.

**Comment by HannesSommer** [comment]
I don't know whether a wrapper is necessary but clearly laser_slam should not depend on PCL if it doesn't need to. Wouldn't  a small package suffice (instead of a wrapper) that depends on PCL and contains the common typedefs and functionalities? On that  laser_slam_ros and segmatch would then depend of course. 
Actually I doubt that you really need these common things. Shall we have a chat about that?

**Comment by rdube** [comment]
Alright it now works! :)

**Comment by HannesSommer** [comment]
Awesome!

**Pull request merged**
